pipeline {
    agent any

    triggers {
            pollSCM('*/3 * * * *')
    }

    stages {
        stage('Build') {
            steps {
                sh 'npm install'
                sh 'npm run build'
            }
        }

        stage('Test') {
            steps {
                sh 'npm test:ci'
            }
        }
    }
}
